/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import yumxpress.dao.CustomerDAO;
import yumxpress.pojo.CustomerPojo;
import yumxpress.util.Mailer;
import yumxpress.util.PasswordEncryption;
import yumxpress.util.Validator;

/**
 *
 * @author PUSHPRAJ
 */
public class CustomerRegistrationFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistrationFrame
     */
    public CustomerRegistrationFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtMobileNo = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 24, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 231, 21));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 24, 32));
        jLabel1.setText("Customer Registration");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/images/login.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        btnRegister.setBackground(new java.awt.Color(255, 231, 21));
        btnRegister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(16, 24, 32));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 441, 130, 36));

        btnBack.setBackground(new java.awt.Color(255, 231, 21));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(16, 24, 32));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 441, 121, 36));

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 231, 21));
        jLabel3.setText("Enter Email ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 79, -1, -1));

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 231, 21));
        jLabel4.setText("Enter Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 146, -1, -1));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 231, 21));
        jLabel5.setText("Enter Mobile No.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 215, -1, -1));

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 231, 21));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 281, -1, -1));

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 231, 21));
        jLabel7.setText("Enter Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 349, -1, -1));

        txtEmailId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 78, 260, -1));

        txtName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 145, 260, -1));

        txtMobileNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 214, 260, -1));

        txtAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 348, 260, -1));

        txtPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(!validateInputs()){
            return;
        }
        try{
            CustomerPojo customer=new CustomerPojo();
            customer.setCustomerName(txtName.getText().trim());
            customer.setEmailId(txtEmailId.getText().trim());
            customer.setMobileNo(txtMobileNo.getText().trim());
            customer.setAddress(txtAddress.getText().trim());
            char [] pwd=txtPassword.getPassword();
//            String pwdStr=new String(pwd);
            String pwdStr=String.valueOf(pwd);
//            AB DATABASE MEI PASSWORD KO ENCRYPT KRKE BHEJENGE NA KI PLAIN TEXT JAISE
            pwdStr=PasswordEncryption.getEncryptedPassword(pwdStr);
            customer.setPassword(pwdStr); 
           boolean result=CustomerDAO.addCustomer(customer);
            if(result){
                JOptionPane.showMessageDialog(null,"Customer Registration Completed Successfully");
                Map<String,String> emailCredentials=new HashMap<>();
                emailCredentials.put("emailId", "oktummyofficialapplication@gmail.com");
                emailCredentials.put("securityKey", "vcng whti uqid iczh");
                Mailer.sendMail(emailCredentials,customer);
                JOptionPane.showMessageDialog(null, "Mail successfully sent to "+customer.getEmailId());
                clearAll();
                return;
            }
            JOptionPane.showMessageDialog(null,"Registration Not Completed!");
        }
        catch(SQLException sql){
            JOptionPane.showMessageDialog(null,"DB Error in CustomerRegistrationFrame");
            sql.printStackTrace();
        }
        catch(MessagingException ex){
            JOptionPane.showMessageDialog(null, "Messaging error in CustomerRegistrationFrame");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new CustomerLoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegistrationFrame().setVisible(true);
            }
        });
    }
    
    public boolean validateInputs() {
        char [] pwd=txtPassword.getPassword();
        if(pwd.length==0 || txtName.getText().trim().isEmpty() || txtMobileNo.getText().trim().isEmpty() || txtEmailId.getText().trim().isEmpty() || txtAddress.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null,"Please enter data in all the fields");
        return false;     
        }
        if(Validator.isValidEmail(txtEmailId.getText().trim())==false){
            JOptionPane.showMessageDialog(null,"Please input valid Email ID");
            return false; 
        }
        if(Validator.isValidMobileNo(txtMobileNo.getText().trim())==false){
            JOptionPane.showMessageDialog(null, "Please input valid contact number");
            return false;
        }
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtEmailId.setText("");
        txtName.setText("");
        txtMobileNo.setText("");
        txtPassword.setText("");
        txtAddress.setText("");
        txtEmailId.requestFocus();
    }
}
