/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDAO;
import yumxpress.dao.OrderDAO;
import yumxpress.dao.ProductDAO;
import yumxpress.pojo.PlaceOrderPojo;
import yumxpress.pojo.ProductPojo;
import yumxpress.util.UserProfile;

/**
 *
 * @author PUSHPRAJ
 */
public class OrderFoodFrame extends javax.swing.JFrame {

    private Map<String,String> companyMap;
    private List<ProductPojo> productList;
    private int listIndex;
    private JFrame showFrame;
    
    public OrderFoodFrame() {
        initComponents();
        setLocationRelativeTo(null);
//        lblUserProfile.setText("Hello "+UserProfile.getUserName().trim());
        this.setResizable(false);
        loadCompanyNames();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMyAccount = new javax.swing.JButton();
        btnMyCart = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblUserProfile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcCompanyNames = new javax.swing.JComboBox<>();
        lblProductImage1 = new javax.swing.JLabel();
        lblProductImage2 = new javax.swing.JLabel();
        lblProductImage3 = new javax.swing.JLabel();
        lblProductImage4 = new javax.swing.JLabel();
        lblProductImage5 = new javax.swing.JLabel();
        lblProductImage6 = new javax.swing.JLabel();
        txtProductName1 = new javax.swing.JTextField();
        txtProductName2 = new javax.swing.JTextField();
        txtProductName3 = new javax.swing.JTextField();
        txtProductName4 = new javax.swing.JTextField();
        txtProductName5 = new javax.swing.JTextField();
        txtProductName6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 24, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 231, 21));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/images/user.png"))); // NOI18N

        btnMyAccount.setBackground(new java.awt.Color(16, 24, 32));
        btnMyAccount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMyAccount.setForeground(new java.awt.Color(255, 231, 21));
        btnMyAccount.setText("My Account");
        btnMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccountActionPerformed(evt);
            }
        });

        btnMyCart.setBackground(new java.awt.Color(16, 24, 32));
        btnMyCart.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMyCart.setForeground(new java.awt.Color(255, 231, 21));
        btnMyCart.setText("My Cart");
        btnMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCartActionPerformed(evt);
            }
        });

        btnCancelOrder.setBackground(new java.awt.Color(16, 24, 32));
        btnCancelOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(255, 231, 21));
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnOrderHistory.setBackground(new java.awt.Color(16, 24, 32));
        btnOrderHistory.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnOrderHistory.setForeground(new java.awt.Color(255, 231, 21));
        btnOrderHistory.setText("Order History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblUserProfile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUserProfile.setForeground(new java.awt.Color(16, 24, 32));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 231, 21));
        jLabel2.setText("Order Food");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/images/icons8-left-arrow-64.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 279, -1, 76));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/images/icons8-right-arrow-64.png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        jPanel1.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 279, -1, 76));

        jLabel5.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("FILTER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 74, -1, -1));

        jcCompanyNames.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jcCompanyNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCompanyNamesActionPerformed(evt);
            }
        });
        jPanel1.add(jcCompanyNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 72, 121, -1));

        lblProductImage1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblProductImage1.setForeground(new java.awt.Color(255, 130, 0));
        lblProductImage1.setText("NA");
        lblProductImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jPanel1.add(lblProductImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 111, 164, 152));

        lblProductImage2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblProductImage2.setForeground(new java.awt.Color(255, 130, 0));
        lblProductImage2.setText("NA");
        lblProductImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jPanel1.add(lblProductImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 111, 168, 152));

        lblProductImage3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblProductImage3.setForeground(new java.awt.Color(255, 130, 0));
        lblProductImage3.setText("NA");
        lblProductImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jPanel1.add(lblProductImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 111, 167, 152));

        lblProductImage4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblProductImage4.setForeground(new java.awt.Color(255, 130, 0));
        lblProductImage4.setText("NA");
        lblProductImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jPanel1.add(lblProductImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 334, 164, 152));

        lblProductImage5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblProductImage5.setForeground(new java.awt.Color(255, 130, 0));
        lblProductImage5.setText("NA");
        lblProductImage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jPanel1.add(lblProductImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 334, 169, 152));

        lblProductImage6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblProductImage6.setForeground(new java.awt.Color(255, 130, 0));
        lblProductImage6.setText("NA");
        lblProductImage6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jPanel1.add(lblProductImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 334, 166, 152));

        txtProductName1.setEditable(false);
        txtProductName1.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jPanel1.add(txtProductName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 276, 164, -1));

        txtProductName2.setEditable(false);
        txtProductName2.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jPanel1.add(txtProductName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 276, 168, -1));

        txtProductName3.setEditable(false);
        txtProductName3.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jPanel1.add(txtProductName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 276, 167, -1));

        txtProductName4.setEditable(false);
        txtProductName4.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jPanel1.add(txtProductName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 493, 164, -1));

        txtProductName5.setEditable(false);
        txtProductName5.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jPanel1.add(txtProductName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 493, 174, -1));

        txtProductName6.setEditable(false);
        txtProductName6.setFont(new java.awt.Font("Goudy Old Style", 1, 16)); // NOI18N
        jPanel1.add(txtProductName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 493, 166, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcCompanyNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCompanyNamesActionPerformed
        String compName=jcCompanyNames.getSelectedItem().toString();
//        AGAR COMPANY NAME ALL HAI TOH FIR HAM YEH NEECHE WALA METHOD CALL KRNA BHI CHORD SKTE HAIN
        String compId=companyMap.get(compName);
//        AGAR ALL SELECT HUA TOH MAP MEI KOI USS NAAM KI KEY HI NHI HOGI AND RETURN NULL HOGA
        if(compId==null){
            compId="ALL";
        }
        try{
            productList=ProductDAO.getAllProductsByCompanyId(compId);
            showDetails();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "DB Error in OrderFoodFrame");
            ex.printStackTrace();
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(null, "Image error in OrderFoodFrame");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jcCompanyNamesActionPerformed

    private void lblOrderProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderProductMouseClicked
        JLabel lbl=(JLabel)evt.getSource();
//        EVT.GETSOURCE RETURN KREGA OBJECT JISKE PAAS KOI BHI METHOD NAHI HAI GETNAME NAAM KA, USSE LBL MEI DOWNCAST KRKE GETNAME CALL KRENGE JISSE ID MIL JAYEGI AND FIR USSE PRODUCT KI DETAILS AJAYEGI
        int index=Integer.parseInt(lbl.getName());
        System.out.println("You clicked on: "+index);
        if(index>=productList.size()){
            JOptionPane.showMessageDialog(null,"Invalid item clicked");
            return;
        }
//        JOptionPane.showMessageDialog(null, "Valid index, item can be booked");
        String [] str={"Add to Cart","Buy Now"};
        int choice=JOptionPane.showOptionDialog(null, "What do you want to do?", "Select an option", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, str, str[1]);
        System.out.println(choice);
        if(choice==0){
//            CODE FOR ADDING PRODUCT IN CART
            ProductPojo p = productList.get(index);
            PlaceOrderPojo ord = new PlaceOrderPojo();
            ord.setProductId(p.getProductId());
            ord.setCustomerId(UserProfile.getUserId().trim());
            ord.setCompanyId(p.getCompanyId());
            try{
                boolean result = OrderDAO.addToCart(ord);
                if(result){
                    JOptionPane.showMessageDialog(null, "Product added to the cart!");
                    return;
                }else{
                    JOptionPane.showMessageDialog(null, "Cannot add the product to cart");
                    return;
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "DB Error while adding product to cart");
                ex.printStackTrace();
            }
        }
        else{
//            CODE FOR DIRECTING THE USER TO BUY THE ITEM
            ProductPojo p=productList.get(index);
            showFrame=new OrderProductFrame(p);
            showFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblOrderProductMouseClicked

    private void btnMyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccountActionPerformed
        new CustomerAccountFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyAccountActionPerformed

    private void btnMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCartActionPerformed
        new CustomerCartFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyCartActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        new CancelOrderFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        new OrderHistoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       new CustomerOptionsFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        listIndex=listIndex-12;
        if(listIndex<0){
            JOptionPane.showMessageDialog(null,"No more items to display, first item reached");
            listIndex=0;
            return;
        }
        showDetails();
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        if(listIndex > productList.size()){
            JOptionPane.showMessageDialog(null,"No more items to display, last item reached");
            return;
        }
        showDetails();
    }//GEN-LAST:event_lblNextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnMyAccount;
    private javax.swing.JButton btnMyCart;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcCompanyNames;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblProductImage1;
    private javax.swing.JLabel lblProductImage2;
    private javax.swing.JLabel lblProductImage3;
    private javax.swing.JLabel lblProductImage4;
    private javax.swing.JLabel lblProductImage5;
    private javax.swing.JLabel lblProductImage6;
    private javax.swing.JLabel lblUserProfile;
    private javax.swing.JTextField txtProductName1;
    private javax.swing.JTextField txtProductName2;
    private javax.swing.JTextField txtProductName3;
    private javax.swing.JTextField txtProductName4;
    private javax.swing.JTextField txtProductName5;
    private javax.swing.JTextField txtProductName6;
    // End of variables declaration//GEN-END:variables

    private void loadCompanyNames() {
        try{
            companyMap=CompanyDAO.getAllCompanyIdAndName();
            Set<String> companyNames=companyMap.keySet();
            jcCompanyNames.addItem("ALL");
            for(String cname:companyNames){
                jcCompanyNames.addItem(cname);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "DB Error in OrderFoodFrame");
            ex.printStackTrace();
        }
    }

    private void showDetails() {
        if(listIndex<productList.size()){
            ProductPojo p=productList.get(listIndex);
            Image img=p.getProductImage();
            img=img.getScaledInstance(lblProductImage1.getWidth(),lblProductImage1.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            lblProductImage1.setIcon(icon);
            txtProductName1.setText(p.getProductName());
            lblProductImage1.setName(listIndex+"");
            txtProductName1.setName(listIndex+"");
            listIndex++;
        }else{
            lblProductImage1.setIcon(null);
            txtProductName1.setText("N/A");
            lblProductImage1.setText("N/A");
            lblProductImage1.setName(listIndex+"");
            txtProductName1.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            ProductPojo p=productList.get(listIndex);
            Image img=p.getProductImage();
            img=img.getScaledInstance(lblProductImage2.getWidth(),lblProductImage2.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            lblProductImage2.setIcon(icon);
            txtProductName2.setText(p.getProductName());
            lblProductImage2.setName(listIndex+"");
            txtProductName2.setName(listIndex+"");
            listIndex++;
        }else{
            lblProductImage2.setIcon(null);
            txtProductName2.setText("N/A");
            lblProductImage2.setText("N/A");
            lblProductImage2.setName(listIndex+"");
            txtProductName2.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            ProductPojo p=productList.get(listIndex);
            Image img=p.getProductImage();
            img=img.getScaledInstance(lblProductImage3.getWidth(),lblProductImage3.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            lblProductImage3.setIcon(icon);
            txtProductName3.setText(p.getProductName());
            lblProductImage3.setName(listIndex+"");
            txtProductName3.setName(listIndex+"");
            listIndex++;
        }else{
            lblProductImage3.setIcon(null);
            txtProductName3.setText("N/A");
            lblProductImage3.setText("N/A");
            lblProductImage3.setName(listIndex+"");
            txtProductName3.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            ProductPojo p=productList.get(listIndex);
            Image img=p.getProductImage();
            img=img.getScaledInstance(lblProductImage4.getWidth(),lblProductImage4.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            lblProductImage4.setIcon(icon);
            txtProductName4.setText(p.getProductName());
            lblProductImage4.setName(listIndex+"");
            txtProductName4.setName(listIndex+"");
            listIndex++;
        }else{
            lblProductImage4.setIcon(null);
            txtProductName4.setText("N/A");
            lblProductImage4.setText("N/A");
            lblProductImage4.setName(listIndex+"");
            txtProductName4.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            ProductPojo p=productList.get(listIndex);
            Image img=p.getProductImage();
            img=img.getScaledInstance(lblProductImage5.getWidth(),lblProductImage5.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            lblProductImage5.setIcon(icon);
            txtProductName5.setText(p.getProductName());
            lblProductImage5.setName(listIndex+"");
            txtProductName5.setName(listIndex+"");
            listIndex++;
        }else{
            lblProductImage5.setIcon(null);
            txtProductName5.setText("N/A");
            lblProductImage5.setText("N/A");
            lblProductImage5.setName(listIndex+"");
            txtProductName5.setName(listIndex+"");
            listIndex++;
        }
        if(listIndex<productList.size()){
            ProductPojo p=productList.get(listIndex);
            Image img=p.getProductImage();
            img=img.getScaledInstance(lblProductImage6.getWidth(),lblProductImage6.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(img);
            lblProductImage6.setIcon(icon);
            txtProductName6.setText(p.getProductName());
            lblProductImage6.setName(listIndex+"");
            txtProductName6.setName(listIndex+"");
            listIndex++;
        }else{
            lblProductImage6.setIcon(null);
            txtProductName6.setText("N/A");
            lblProductImage6.setText("N/A");
            lblProductImage6.setName(listIndex+"");
            txtProductName6.setName(listIndex+"");
            listIndex++;
        }
    }
    
}
